### ISSUE TITLE
Issue on getting the subscription packets

### ISSUE THREAD

**Issue by Roger14** [DitchOoM/mqtt#7]
Hi,
 
    Thanks for the quick answers on the last reported issue. Appreciate it.

    I followed your recommendations and tried to publish and subscribe to the same topic.
    In addition, I deployed another standalone MQTT client connecting to the same broker, to listen to the topic.
    Below are the key codes:
    

`client.subscribe("test/a", QualityOfService.AT_LEAST_ONCE)   ` 

```
client.observe(Topic.fromOrThrow("test/+", Topic.Type.Filter)).collect{
       println("$it.topic | $it.payload")
}
```

```
val payloadBuffer = PlatformBuffer.allocate(payload.length, AllocationZone.SharedMemory)
payloadBuffer.writeString("abc") 
client.publish("test/a", QualityOfService.EXACTLY_ONCE, payloadBuffer, false)
```

   The result was that after I published using the above codes, the standalone MQTT client was able to receive the message.
   However, the above observe flow didn't get called and didn't receive any message.

   May I know is there something which I did wrongly?
   Thanks for your time, once again. :)

_Originally posted by @Roger14 in https://github.com/DitchOoM/mqtt/issues/6#issuecomment-1790504543_

**Comment by thebehera** [comment]
Can you post a full code sample?  Off the top of my head I'm assuming that your process is ending too quickly to receive the published message. 
I just tried this example on the JVM and it worked for me. Note that we are collecting from the flow in a new coroutine (`launch`) and the `pubOperation.awaitAll()` which suspends until the publish has been fully ack'd.

You might not need to `awaitAll()` in production code but that depends on how you are using MQTT. I imagine in most cases MQTT is alive and running as long as the entire application is running. When writing test code which completes immediately, you need to await until the step has completed. I can see where your confusion is coming from, maybe I need to make it clear these are functions that start async work in which you can call `await` before going to the next step.

```
val service = MqttService.buildNewService(ipcEnabled = true, inMemory = false)
val socketEndpoint = MqttConnectionOptions.SocketConnection(host = "test.mosquitto.org", port = 1883)
val connectionRequest = ConnectionRequest(clientId = "testClient")
val client = service.addBrokerAndStartClient(socketEndpoint, connectionRequest)
// client is connected
client.subscribe("testMqttTopic/+", QualityOfService.EXACTLY_ONCE)
val flow = client.observe(Topic.fromOrThrow("testMqttTopic/+", Topic.Type.Filter))
// or val flow = subscribeOperation.subscriptions.values.first()
launch { // launch a new coroutine
    flow.collect {
        println("${it.topic} ${it.qualityOfService} | ${it.payload}")
        cancel() // cancel this job after we receive the first pub
    }
}
val payloadBuffer = PlatformBuffer.allocate(4)
payloadBuffer.writeString("taco") // just write utf8 string data for now

val pubOperation = client.publish("testMqttTopic/123", QualityOfService.EXACTLY_ONCE, payloadBuffer)
pubOperation.awaitAll() // suspend until publish is fully ack'd based on qos

client.unsubscribe("testMqttTopic/+").unsubAck.await() // unsubscribe and await ack
client.shutdown()
```

**Comment by thebehera** [comment]
Feel free to re-open if there are any issues left, thanks!
